fix[bug] issue compatibility with LP new version 4.2.2.3
orangerdev/sejoli-learnpress-integration pull request #4
Opened 2023-03-27 21:47 UTC by asdzakky

2023-03-27 22:52 UTC, orangerdev requested changes

2023-03-27 22:52 UTC, orangerdev commented on functions/user.php
> +    if( $learnpress_version <= '4.2.2.2' ) :
[pakai fungsi php version_compare](https://www.php.net/manual/en/function.version-compare.php)

2023-03-27 23:06 UTC, asdzakky commented on functions/user.php
> +    if( $learnpress_version <= '4.2.2.2' ) :
ok done pak @orangerdev

2023-03-30 05:32 UTC, orangerdev requested changes

2023-03-30 05:32 UTC, orangerdev commented on functions/user.php
> +    if( $learnpress_version <= '4.2.2.2' ) :
eh ini kok belum berubah ya mas?

2023-03-30 07:13 UTC, asdzakky commented on functions/user.php
> +    if( $learnpress_version <= '4.2.2.2' ) :
lah iiya kok gk berubah ya, udh sy push pdhal, cba sy cek lg pak

2023-04-02 12:28 UTC, orangerdev approved these changes

2023-04-02 12:29 UTC, merged